### ISSUE TITLE
Помилка в URL

### ISSUE THREAD

**Issue by nazar1ua** [vuejsorgua/docs#26]
https://vuejs.org.ua/guide/introduction.html#стиnі-api

замість

https://vuejs.org.ua/guide/introduction.html#стилі-api

**Comment by nazar1ua** [comment]
Я не знаю, в чому проблема

**Comment by matrunchyk** [comment]
Так і має бути. Це баг в транслітерації під час парсингу в самому Vitepress. Тобто, це проблема в [upstream](https://github.com/vuejs/vitepress/issues/299)

**Comment by matrunchyk** [comment]
Хоча, перевідкрию, щоб коли пофіксять — можна було цей issue пофіксити в нас теж.

**Comment by nazar1ua** [comment]
Так що навряд-чи це колись вирішиться

**Comment by matrunchyk** [comment]
Так, треба перевідкрити в апстрімі (ну або при бажанні/можливості пофіксити в апстрімі)). 
Пофіксять — перевідкриємо)

**Comment by nazar1ua** [comment]
Ця проблема вирішена в новій альфа-версії vitepress. теоритично треба переписувати і @vuejs/docs, і @vuejs/theme, і це тільки тоді, коли ця альфа-версія стане стабільною
